export const SHAREABLE_RESOURCES = {
  document: {
    table: 'documents',
    module: 'documents',
    fields: 'number, title, description, version, status, review_date, file_name, created_at, updated_at',
    categorySource: 'documents',
    labelField: 'title',
  },
  capa: {
    table: 'capas',
    module: 'capas',
    fields: 'number, title, origin, description, service, priority, severity, status, due_date, root_cause, corrective_action, preventive_action, effectiveness_verified, effectiveness_notes, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'title',
  },
  complaint: {
    table: 'complaints',
    module: 'complaints',
    fields: 'customer_name, received_date, due_date, description, product_service, severity, status, root_cause, resolution, resolution_date, customer_satisfied, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'customer_name',
  },
  qqoqccp: {
    table: 'qqoqccp_analyses',
    module: 'qqoqccp',
    fields: 'title, qui, quoi, ou_, quand_, comment_, combien, pourquoi, ai_synthesis, status, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'title',
  },
  procedure: {
    table: 'procedures',
    module: 'procedures',
    fields: 'number, title, process, status, next_review_date, current_version_id, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'title',
  },
  accident: {
    table: 'accidents',
    module: 'accidents',
    fields: 'title, incident_type, occurred_at, occurred_time, location, injury_type, injury_location, witness_name, description, immediate_cause, immediate_actions, root_cause, severity, with_lost_time, lost_days, status, closed_at, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'title',
  },
  pdca: {
    table: 'pdca_projects',
    module: 'pdca',
    fields: 'title, description, target_date, status, plan_content, plan_completed_at, plan_due_date, do_content, do_completed_at, do_due_date, check_content, check_completed_at, check_due_date, act_content, act_completed_at, act_due_date, closed_at, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'title',
  },
  audit: {
    table: 'audits',
    module: 'audits',
    fields: 'title, audit_type, scope, planned_date, completed_date, status, conclusion, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'title',
  },
  management_review: {
    table: 'management_reviews',
    module: 'management-reviews',
    fields: 'title, review_date, period_start, period_end, status, participants, previous_actions_status, context_changes, resource_adequacy, improvement_opportunities, conclusions, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'title',
  },
  risk: {
    table: 'risks',
    module: 'risks',
    fields: 'title, type, category, description, likelihood, impact, risk_score, current_controls, treatment_plan, residual_likelihood, residual_impact, residual_score, status, review_date, last_reviewed_at, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'title',
  },
  haccp_plan: {
    table: 'haccp_plans',
    module: 'haccp',
    fields: 'title, product_description, scope, team, prerequisites, intended_use, consumer_groups, product_characteristics, flow_diagram_reference, flow_diagram_verification, no_ccp_justification, validation_review_notes, verification_review_notes, status, review_date, last_reviewed_at, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'title',
  },
  supplier: {
    table: 'suppliers',
    module: 'suppliers',
    fields: 'name, category, contact_name, contact_email, contact_phone, criticality, status, next_evaluation_date, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'name',
  },
  nonconforming_output: {
    table: 'nonconforming_outputs',
    module: 'nonconforming-outputs',
    fields: 'title, description, detected_at, lot_reference, containment_action, disposition, action_taken, concession_reference, customer_informed, status, closed_at, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'title',
  },
  customer_satisfaction: {
    table: 'customer_satisfaction_surveys',
    module: 'customer-satisfaction',
    fields: 'customer_name, survey_date, method, score, comments, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'customer_name',
  },
  employee: {
    table: 'employees',
    module: 'employees',
    fields: 'full_name, job_title, email, is_active, created_at',
    categorySource: 'generic',
    labelField: 'full_name',
  },
  training: {
    table: 'trainings',
    module: 'trainings',
    fields: 'title, type, frequency_months, location, instructor, duration, description, summary, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'title',
  },
  kpi: {
    table: 'kpis',
    module: 'kpis',
    fields: 'name, unit, target, target_direction, frequency, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'name',
  },
  task: {
    table: 'tasks',
    module: 'planning',
    fields: 'title, description, due_date, status, priority, checklist, recurrence, recurrence_interval, created_at, updated_at',
    categorySource: 'generic',
    labelField: 'title',
  },
  service: {
    table: 'services',
    module: 'services',
    fields: 'name, description, is_active, created_at',
    labelField: 'name',
  },
  quality_policy: {
    table: 'quality_policy_versions',
    module: 'documents',
    fields: 'content, created_at',
  },
};
